spring.cloud.function.definition=transform
spring.cloud.stream.function.bindings.transform-in-0=input
spring.cloud.stream.function.bindings.transform-out-0=output
spring.cloud.stream.bindings.input.destination=dataIn
spring.cloud.stream.bindings.input.binder=nats
spring.cloud.stream.bindings.output.destination=dataOut
spring.cloud.stream.bindings.output.binder=nats
nats.spring.server=nats://localhost:4222
