name: Build Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GODEBUG: x509sha1=1
    steps:
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
      - name: Install Nats Server
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go build main.go
          mkdir -p ~/.local/bin
          cp main ~/.local/bin/nats-server
          cd ..
          rm -rf nats-server
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 17
      - name: Build and Install Parent Pom
        run: mvn --no-transfer-progress -N clean install
      - name: Build and Install Samples
        run: |
          cd nats-spring-samples
          mvn --no-transfer-progress -N clean install
          cd ..
      - name: Compile and Test
        run: mvn --no-transfer-progress clean compile test
