name: Build Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.SIGNING_PASSWORD }}
      MAVEN_GPG_KEY: ${{ secrets.SIGNING_KEY }}
      GODEBUG: x509sha1=1
    steps:
      - name: Setup GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.4'
      - name: Install Nats Server
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://github.com/nats-io/nats-server.git
          cd nats-server
          go get
          go build main.go
          mkdir -p ~/.local/bin
          cp main ~/.local/bin/nats-server
          cd ..
          rm -rf nats-server
          nats-server -v
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0
        with:
          java-version: 17
      - name: Build and Install Parent Pom
        run: mvn --no-transfer-progress --settings ./settings.xml -N clean install
      - name: Build and Install Samples
        run: |
          cd nats-spring-samples
          mvn --no-transfer-progress --settings ../settings.xml -N clean install
          cd ..
      - name: Publish
        run: mvn --no-transfer-progress --settings ./settings.xml clean verify install deploy



